modified:   armada/mk_uSD_Image 	new file:   dpdk_scripts/setup_env   Add DPDK setup_env to configure you x86 environment to crosscompile a downloaded dpdk release. Also cleaned up the mk_uSD_Image script

diff --git a/armada/mk_uSD_Image b/armada/mk_uSD_Image
--- a/armada/mk_uSD_Image
+++ b/armada/mk_uSD_Image
@@ -6,8 +6,6 @@
 #                            recover / fix the third Partition
 #    Third Partiton > bulk of storage
 
-
-
 REL_NAME=SDK-10.1.1-PR1
 
 #TARGET_DIR=a80x0_mcbin_single_shot-release-output
@@ -16,11 +14,9 @@ REL_NAME=SDK-10.1.1-PR1
 TARGET_DIR=a37xx_espressobin_1000_800-release-output
 TARGET_NAME=armada-3720-espressobin
 
-
 GREEN=$'\e[32m'
 RED=$'\e[31m'
 NORMAL=$'\e[0m'
-
 
 Banner() {
 echo ""
@@ -29,7 +25,6 @@ echo "* $1"
 echo "********"
 }
 
-
 #***************
 # banner " Must be root from here out "
 usrname=$(whoami)
@@ -37,8 +32,6 @@ if [ $usrname != "root" ] ; then
    echo "Need to be root.  Exiting script"
    exit 1
 fi
-
-
 
 #command line check see - see if the number of arguments is zero
 if [ $# -eq 0 ] ; then
@@ -50,9 +43,6 @@ if [ $# -eq 0 ] ; then
   echo $NORMAL
    exit
 fi
-
-
-
 
 BLOCK_DEVICE="$1"
 PARTITION_1="$1"1
@@ -94,15 +84,11 @@ if [ "$CHK_MOUNTED" != "" ];then
    exit 1
 fi
 
-
-
 pushd  $TARGET_DIR/
    cd images/
    dd if=flash-image.bin of=/dev/sdc1
    mkfs.ext4 /dev/sdc2
    mkfs.ext4 /dev/sdc3
-
-
 
    mount /dev/sdc2 /mnt
    mkdir /mnt/boot
@@ -119,12 +105,21 @@ pushd  $TARGET_DIR/
       echo "missing $PWD/$TARGET_NAME.dtb " 
       exit 1
    fi
+    if [ ! -f flash-image.bin ] ; then
+      echo "missing $PWD/flash-image.bin " 
+      exit 1
+   fi
 
-   cp rootfs.tar /mnt/.
-   cp Image /mnt/boot/Image_$REL_NAME
+
+   cp rootfs.tar       /mnt/.
+   cp rootfs.tar       /mnt/root/rootfs.tar_$REL_NAME
+   cp flash-image.bin  /mnt/.
+   cp flash-image.bin  /mnt/root/flash-image.bin_$REL_NAME
+ 
+   cp Image             /mnt/boot/Image
+   cp Image             /mnt/boot/Image_$REL_NAME
+   cp $TARGET_NAME.dtb  /mnt/boot/dtb
    cp $TARGET_NAME.dtb  /mnt/boot/$TARGET_NAME.dtb_$REL_NAME
-   cp $TARGET_NAME.dtb  /mnt/boot/dtf.dtb
-   cp rootfs.tar /mnt/root/.
    rm -rf /mnt/lost+found
 
  
